#!/bin/bash
set -e

if [ "$1" == "delete-first" ]; then
  echo "•• Parando o contêiner"
  docker stop web_wp  2> /dev/null
  echo "•• Removendo o contêiner"
  docker rm web_wp 2> /dev/null
  echo "•• Removendo o site do VOLUME"
  rm -rf site/* 2> /dev/null
  git checkout -- site/README.md
fi

# docker run --rm -i -t --name web_wp -p 80:80 -p 2285:22 parana/jessie-wordpress
# docker run -i -t --rm --name web_wp \
docker run -d --name web_wp \
    -v $PWD/site:/var/www/html \
    -p 80:80 -p 2285:22 \
    -e ROOT_PASSWORD=xyz  \
    -e WP_EMAIL_ADDR=joao.parana@gmail.com \
    parana/jessie-wordpress start-wordpress

echo Contêiner web_wp iniciado com WEB na porta 80 e ssh na porta 2285
echo "Use:  open http://`boot2docker ip`:80 para testar"
echo "docker logs web_wp 2> /dev/null | grep  \"senha de root\" "
# ssh -p 2285 root@$(docker-ip)
echo "Aguardando 40 segundos ..."
sleep 40
echo "Testando o suporte a PHP ..."
cp test/site/testecli.php site
docker exec web_wp php /var/www/html/testecli.php
docker logs web_wp
echo "Quando desejar, execute novamente: docker logs web_wp"
