#!/bin/bash
set -e

# O Apache não se comporta muito bem com arquivos PID de sessões anteriores
rm -f /var/run/apache2/apache2.pid
echo "••• `date` - Apache Vai iniciar "
/usr/local/bin/apache2-foreground
echo "••• `date` - Apache Terminou "
